apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: vectordb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: password

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: ankane/pgvector
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-config
